package dev.vepo.youtube.creator.project;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.bson.types.ObjectId;
import org.junit.jupiter.api.Test;

import dev.vepo.youtube.creator.shared.UnitTest;

@UnitTest
class ProjectTest {

    @Test
    void newProjectUsesFullHdAnd30FpsDefaults() {
        var project = new Project();

        assertEquals(ScreenSize.HD_1080p, project.getScreenSize());
        assertEquals(FrameRate.FPS_30_WEB, project.getFrameRate());
        assertEquals(1000L * 60 * 30, project.getDuration());
    }

    @Test
    void newProjectHasEmptyMediaAndClips() {
        var project = new Project();

        assertTrue(project.getMedias().isEmpty());
        assertTrue(project.getClips().isEmpty());
    }

    @Test
    void newProjectReceivesAutoGeneratedName() {
        var project = new Project();

        assertTrue(project.getName().startsWith("Project"));
    }

    @Test
    void projectsAreEqualWhenTheyShareTheSameId() {
        var id = new ObjectId();
        var first = new Project();
        first.setId(id);
        var second = new Project();
        second.setId(id);

        assertEquals(first, second);
    }

    @Test
    void projectCanBeSerializedToJson() throws Exception {
        var project = new Project();

        var json = project.asJson();

        assertNotNull(json);
        assertTrue(json.contains(project.getName()));
    }
}
